# Generated by Django 5.2.17 on 2026-08-23 22:02

import apps.operations.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direct_source_code', models.SlugField(blank=True, max_length=64)),
                ('client_subject_ref', models.UUIDField(db_index=True)),
                ('organization_fingerprint', models.CharField(blank=True, db_index=True, max_length=64, validators=[apps.operations.models.validate_sha256_digest])),
                ('contact_fingerprint', models.CharField(blank=True, db_index=True, max_length=64, validators=[apps.operations.models.validate_sha256_digest])),
                ('commercial_context', models.JSONField(blank=True, default=dict, validators=[apps.operations.models.validate_safe_json])),
                ('current_status', models.CharField(blank=True, choices=[('ASSISTED_DRAFT', 'Assisted draft'), ('LEAD_CREATED', 'Lead created'), ('PHONE_VERIFIED', 'Phone verified'), ('CONSENTS_CONFIRMED', 'Consents confirmed'), ('QUALIFICATION_STARTED', 'Qualification started'), ('NEEDS_CLARIFICATION', 'Needs clarification'), ('QUALIFIED', 'Qualified'), ('NOT_QUALIFIED', 'Not qualified'), ('DUPLICATE', 'Duplicate'), ('SOURCE_NOT_ALLOWED', 'Source not allowed'), ('CONSENT_INVALID', 'Consent invalid'), ('ROUTING_DECIDED', 'Routing decided'), ('SENT_TO_ADVERTISER', 'Sent to advertiser'), ('DELIVERY_CONFIRMED', 'Delivery confirmed'), ('ADVERTISER_ACCEPTED', 'Advertiser accepted'), ('ADVERTISER_REJECTED', 'Advertiser rejected'), ('CLIENT_CONTACTED', 'Client contacted'), ('DOCUMENTS_REQUESTED', 'Documents requested'), ('PRE_APPROVED', 'Pre-approved'), ('APPROVED', 'Approved'), ('CONTRACT_SIGNED', 'Contract signed'), ('PRODUCT_ACTIVATED', 'Asset delivered or product activated'), ('PAYOUT_EXPECTED', 'Payout expected'), ('PAYOUT_APPROVED', 'Payout approved'), ('RECONCILIATION_RECEIVED', 'Reconciliation received'), ('INVOICED', 'Invoiced'), ('CASH_RECEIVED', 'Cash received'), ('PARTNER_ACCRUAL_CREATED', 'Partner accrual created'), ('PARTNER_PAID', 'Partner paid'), ('CANCELLED', 'Cancelled')], max_length=40)),
                ('current_status_at', models.DateTimeField(blank=True, null=True)),
                ('is_test', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
            bases=(apps.operations.models.ValidatedModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Advertiser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('DISCOVERY', 'Discovery'), ('COMPATIBLE', 'Compatible'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('REJECTED', 'Rejected')], default='DISCOVERY', max_length=16)),
                ('acknowledgement_sla_minutes', models.PositiveIntegerField(default=60)),
                ('first_contact_sla_minutes', models.PositiveIntegerField(default=30)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['status', 'code'], name='ops_advertiser_status_idx')],
            },
            bases=(apps.operations.models.ValidatedModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CashReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_reference', models.CharField(max_length=128)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('distributable_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='RUB', max_length=3)),
                ('evidence_reference', models.CharField(max_length=255)),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_receipts', to='operations.advertiser')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_receipts', to='operations.lead')),
            ],
            options={
                'ordering': ['-received_at'],
            },
            bases=(apps.operations.models.ImmutableCreateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ConsentTextVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consent_type', models.CharField(choices=[('PROCESSING', 'Personal data processing'), ('TRANSFER', 'Personal data transfer'), ('MARKETING', 'Marketing communications'), ('CALL_RECORDING', 'Call recording')], max_length=24)),
                ('version', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('text_digest', models.CharField(max_length=64, validators=[apps.operations.models.validate_sha256_digest])),
                ('public_reference', models.CharField(blank=True, max_length=255)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['consent_type', 'version'],
                'constraints': [models.UniqueConstraint(fields=('consent_type', 'version'), name='ops_unique_consent_text_version')],
            },
            bases=(apps.operations.models.ImmutableAfterPublishMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AttributionSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner_id_snapshot', models.UUIDField(blank=True, null=True)),
                ('partner_source_id_snapshot', models.UUIDField(blank=True, null=True)),
                ('click_id', models.CharField(blank=True, max_length=128)),
                ('signed_token_digest', models.CharField(blank=True, max_length=64, validators=[apps.operations.models.validate_sha256_digest])),
                ('utm_source', models.CharField(blank=True, max_length=128)),
                ('utm_medium', models.CharField(blank=True, max_length=128)),
                ('utm_campaign', models.CharField(blank=True, max_length=128)),
                ('utm_content', models.CharField(blank=True, max_length=128)),
                ('utm_term', models.CharField(blank=True, max_length=128)),
                ('landing_variant', models.CharField(blank=True, max_length=64)),
                ('referrer_domain', models.CharField(blank=True, max_length=255)),
                ('first_touch_at', models.DateTimeField()),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='attribution', to='operations.lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
            bases=(apps.operations.models.ImmutableCreateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('product_type', models.CharField(choices=[('LEASING', 'Leasing'), ('RKO', 'Settlement account'), ('FACTORING', 'Factoring'), ('GUARANTEE', 'Bank guarantee'), ('ACQUIRING', 'Acquiring'), ('OTHER', 'Other B2B product')], max_length=24)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('CLOSED', 'Closed')], default='DRAFT', max_length=16)),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='operations.advertiser')),
            ],
            options={
                'ordering': ['advertiser__name', 'name'],
            },
            bases=(apps.operations.models.ValidatedModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='OfferTermsVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('target_action', models.CharField(max_length=128)),
                ('payout_model', models.CharField(choices=[('FIXED', 'Fixed'), ('PERCENT', 'Percentage'), ('REVSHARE', 'Revenue share'), ('HYBRID', 'Hybrid')], max_length=16)),
                ('payout_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('payout_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('currency', models.CharField(default='RUB', max_length=3)),
                ('hold_days', models.PositiveIntegerField(default=0)),
                ('dedup_window_days', models.PositiveIntegerField(default=0)),
                ('attribution_window_days', models.PositiveIntegerField(default=30)),
                ('allow_own_landing', models.BooleanField(default=False)),
                ('allow_professional_partners', models.BooleanField(default=False)),
                ('allow_paid_nonbrand_search', models.BooleanField(default=False)),
                ('allow_rerouting', models.BooleanField(default=False)),
                ('terms_digest', models.CharField(max_length=64, validators=[apps.operations.models.validate_sha256_digest])),
                ('rules', models.JSONField(blank=True, default=dict, validators=[apps.operations.models.validate_safe_json])),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='terms_versions', to='operations.offer')),
            ],
            options={
                'ordering': ['offer', 'version'],
            },
            bases=(apps.operations.models.ImmutableAfterPublishMixin, models.Model),
        ),
        migrations.AddField(
            model_name='lead',
            name='offer_terms_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='operations.offertermsversion'),
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('CLOSED', 'Closed')], default='DRAFT', max_length=16)),
                ('contract_reference', models.CharField(blank=True, max_length=128)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['status', 'code'], name='ops_partner_status_idx')],
            },
            bases=(apps.operations.models.ValidatedModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PartnerAccrual',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='RUB', max_length=3)),
                ('rate_basis', models.CharField(max_length=255)),
                ('cash_receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partner_accruals', to='operations.cashreceipt')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accruals', to='operations.partner')),
            ],
            options={
                'ordering': ['cash_receipt', 'partner'],
            },
            bases=(apps.operations.models.ImmutableCreateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PartnerAccrualAdjustment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reason_code', models.CharField(max_length=64)),
                ('evidence_reference', models.CharField(max_length=255)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('partner_accrual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='operations.partneraccrual')),
            ],
            options={
                'ordering': ['partner_accrual', 'occurred_at'],
            },
            bases=(apps.operations.models.ImmutableCreateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PartnerOfferTerms',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('reward_model', models.CharField(choices=[('FIXED', 'Fixed amount'), ('PERCENT_OF_RECEIPT', 'Percentage of distributable cash')], max_length=24)),
                ('fixed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('receipt_share_percent', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('hold_days', models.PositiveIntegerField(default=0)),
                ('terms_digest', models.CharField(max_length=64, validators=[apps.operations.models.validate_sha256_digest])),
                ('offer_terms_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partner_terms', to='operations.offertermsversion')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offer_terms', to='operations.partner')),
            ],
            options={
                'ordering': ['partner', 'offer_terms_version', 'version'],
            },
            bases=(apps.operations.models.ImmutableAfterPublishMixin, models.Model),
        ),
        migrations.AddField(
            model_name='partneraccrual',
            name='partner_offer_terms',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accruals', to='operations.partnerofferterms'),
        ),
        migrations.CreateModel(
            name='PartnerSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=64)),
                ('source_type', models.CharField(choices=[('EMBEDDED', 'Embedded professional partner'), ('PAID_SEARCH', 'Paid search'), ('SEO', 'Organic search'), ('TELEGRAM', 'Telegram'), ('REFERRAL', 'Referral'), ('OTHER', 'Other approved source')], max_length=24)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('SUSPENDED', 'Suspended'), ('REJECTED', 'Rejected')], default='PENDING', max_length=16)),
                ('allowed_channels', models.JSONField(blank=True, default=list, validators=[apps.operations.models.validate_safe_json])),
                ('monthly_cap', models.PositiveIntegerField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sources', to='operations.partner')),
            ],
            options={
                'ordering': ['partner__name', 'code'],
            },
            bases=(apps.operations.models.ValidatedModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='lead',
            name='partner_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='operations.partnersource'),
        ),
        migrations.CreateModel(
            name='StatusEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('status_code', models.CharField(choices=[('ASSISTED_DRAFT', 'Assisted draft'), ('LEAD_CREATED', 'Lead created'), ('PHONE_VERIFIED', 'Phone verified'), ('CONSENTS_CONFIRMED', 'Consents confirmed'), ('QUALIFICATION_STARTED', 'Qualification started'), ('NEEDS_CLARIFICATION', 'Needs clarification'), ('QUALIFIED', 'Qualified'), ('NOT_QUALIFIED', 'Not qualified'), ('DUPLICATE', 'Duplicate'), ('SOURCE_NOT_ALLOWED', 'Source not allowed'), ('CONSENT_INVALID', 'Consent invalid'), ('ROUTING_DECIDED', 'Routing decided'), ('SENT_TO_ADVERTISER', 'Sent to advertiser'), ('DELIVERY_CONFIRMED', 'Delivery confirmed'), ('ADVERTISER_ACCEPTED', 'Advertiser accepted'), ('ADVERTISER_REJECTED', 'Advertiser rejected'), ('CLIENT_CONTACTED', 'Client contacted'), ('DOCUMENTS_REQUESTED', 'Documents requested'), ('PRE_APPROVED', 'Pre-approved'), ('APPROVED', 'Approved'), ('CONTRACT_SIGNED', 'Contract signed'), ('PRODUCT_ACTIVATED', 'Asset delivered or product activated'), ('PAYOUT_EXPECTED', 'Payout expected'), ('PAYOUT_APPROVED', 'Payout approved'), ('RECONCILIATION_RECEIVED', 'Reconciliation received'), ('INVOICED', 'Invoiced'), ('CASH_RECEIVED', 'Cash received'), ('PARTNER_ACCRUAL_CREATED', 'Partner accrual created'), ('PARTNER_PAID', 'Partner paid'), ('CANCELLED', 'Cancelled')], max_length=40)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor_type', models.CharField(choices=[('SYSTEM', 'System'), ('OPERATOR', 'Operator'), ('PARTNER', 'Partner'), ('ADVERTISER', 'Advertiser'), ('FINANCE', 'Finance')], max_length=16)),
                ('actor_ref', models.CharField(blank=True, max_length=120)),
                ('source_system', models.CharField(default='finuslugi', max_length=64)),
                ('reason_code', models.CharField(blank=True, max_length=64)),
                ('external_reference', models.CharField(blank=True, max_length=128)),
                ('metadata', models.JSONField(blank=True, default=dict, validators=[apps.operations.models.validate_safe_json])),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_events', to='operations.lead')),
            ],
            options={
                'ordering': ['lead', 'sequence'],
            },
            bases=(apps.operations.models.ImmutableCreateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CashAdjustment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reason_code', models.CharField(max_length=64)),
                ('evidence_reference', models.CharField(max_length=255)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('cash_receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='operations.cashreceipt')),
            ],
            options={
                'ordering': ['cash_receipt', 'occurred_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount', 0), _negated=True), name='ops_cash_adjustment_nonzero')],
            },
            bases=(apps.operations.models.ImmutableCreateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ConsentEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_at', models.DateTimeField()),
                ('channel', models.CharField(choices=[('WEB_CHECKBOX', 'Web checkbox'), ('SMS_OTP', 'SMS OTP'), ('SIGNED_LINK', 'Signed link'), ('OTHER', 'Other approved channel')], max_length=24)),
                ('subject_ref', models.UUIDField()),
                ('evidence_digest', models.CharField(max_length=64, validators=[apps.operations.models.validate_sha256_digest])),
                ('ip_digest', models.CharField(blank=True, max_length=64, validators=[apps.operations.models.validate_sha256_digest])),
                ('user_agent_digest', models.CharField(blank=True, max_length=64, validators=[apps.operations.models.validate_sha256_digest])),
                ('recipient_list_version', models.CharField(blank=True, max_length=64)),
                ('proof_reference', models.CharField(blank=True, max_length=255)),
                ('consent_text_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence', to='operations.consenttextversion')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consent_evidence', to='operations.lead')),
            ],
            options={
                'ordering': ['lead', 'confirmed_at'],
                'constraints': [models.UniqueConstraint(fields=('lead', 'consent_text_version'), name='ops_unique_lead_consent_evidence')],
            },
            bases=(apps.operations.models.ImmutableCreateMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='cashreceipt',
            constraint=models.UniqueConstraint(fields=('advertiser', 'external_reference'), name='ops_unique_advertiser_cash_ref'),
        ),
        migrations.AddConstraint(
            model_name='cashreceipt',
            constraint=models.CheckConstraint(condition=models.Q(('gross_amount__gt', 0)), name='ops_cash_gross_positive'),
        ),
        migrations.AddConstraint(
            model_name='cashreceipt',
            constraint=models.CheckConstraint(condition=models.Q(('distributable_amount__gte', 0)), name='ops_cash_distributable_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='cashreceipt',
            constraint=models.CheckConstraint(condition=models.Q(('distributable_amount__lte', models.F('gross_amount'))), name='ops_cash_distributable_lte_gross'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['status', 'product_type'], name='ops_offer_status_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='offer',
            constraint=models.UniqueConstraint(fields=('advertiser', 'code'), name='ops_unique_offer_code'),
        ),
        migrations.AddConstraint(
            model_name='offertermsversion',
            constraint=models.UniqueConstraint(fields=('offer', 'version'), name='ops_unique_offer_terms_version'),
        ),
        migrations.AddConstraint(
            model_name='offertermsversion',
            constraint=models.CheckConstraint(condition=models.Q(('payout_amount__isnull', True), ('payout_amount__gte', 0), _connector='OR'), name='ops_offer_payout_amount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='offertermsversion',
            constraint=models.CheckConstraint(condition=models.Q(('payout_rate__isnull', True), models.Q(('payout_rate__gte', 0), ('payout_rate__lte', 100)), _connector='OR'), name='ops_offer_payout_rate_range'),
        ),
        migrations.AddConstraint(
            model_name='partneraccrualadjustment',
            constraint=models.CheckConstraint(condition=models.Q(('amount', 0), _negated=True), name='ops_accrual_adjustment_nonzero'),
        ),
        migrations.AddConstraint(
            model_name='partnerofferterms',
            constraint=models.UniqueConstraint(fields=('partner', 'offer_terms_version', 'version'), name='ops_unique_partner_offer_terms'),
        ),
        migrations.AddConstraint(
            model_name='partnerofferterms',
            constraint=models.CheckConstraint(condition=models.Q(('fixed_amount__isnull', True), ('fixed_amount__gte', 0), _connector='OR'), name='ops_partner_fixed_amount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='partnerofferterms',
            constraint=models.CheckConstraint(condition=models.Q(('receipt_share_percent__isnull', True), models.Q(('receipt_share_percent__gte', 0), ('receipt_share_percent__lte', 100)), _connector='OR'), name='ops_partner_share_range'),
        ),
        migrations.AddConstraint(
            model_name='partneraccrual',
            constraint=models.UniqueConstraint(fields=('cash_receipt', 'partner'), name='ops_unique_receipt_partner_accrual'),
        ),
        migrations.AddConstraint(
            model_name='partneraccrual',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ops_partner_accrual_positive'),
        ),
        migrations.AddIndex(
            model_name='partnersource',
            index=models.Index(fields=['status', 'source_type'], name='ops_source_status_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='partnersource',
            constraint=models.UniqueConstraint(fields=('partner', 'code'), name='ops_unique_partner_source'),
        ),
        migrations.AddConstraint(
            model_name='partnersource',
            constraint=models.CheckConstraint(condition=models.Q(('monthly_cap__isnull', True), ('monthly_cap__gt', 0), _connector='OR'), name='ops_partner_source_cap_positive'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['current_status', 'created_at'], name='ops_lead_status_time_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['organization_fingerprint', 'created_at'], name='ops_lead_org_fp_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('partner_source__isnull', False), ('direct_source_code', '')), models.Q(('partner_source__isnull', True), models.Q(('direct_source_code', ''), _negated=True)), _connector='OR'), name='ops_lead_exactly_one_source'),
        ),
        migrations.AddIndex(
            model_name='statusevent',
            index=models.Index(fields=['lead', 'occurred_at'], name='ops_status_lead_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='statusevent',
            constraint=models.UniqueConstraint(fields=('lead', 'sequence'), name='ops_unique_lead_sequence'),
        ),
    ]
