# Generated by Django 5.2.17 on 2026-08-23 22:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='fingerprint_key_version',
            field=models.PositiveSmallIntegerField(default=1, help_text='Version of the secret key used for HMAC-SHA-256 fingerprints', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
